### ISSUE TITLE
Unreadable log on server

### ISSUE THREAD

**Issue by lightness** [tresdosdos/poll-app#3]
```
{"level":50,"time":1535478520676,"msg":"No db connection","pid":12944,"hostname":"WS-020-11","v":1}
{"level":50,"time":1535478520677,"msg":"password authentication failed for user \"Uladzimir.Aleshka\"","pid":12944,"hostname":"WS-020-11","type":"Error","stack":"error: password authentication failed for user \"Uladzimir.Aleshka\"\n    at Connection.parseE (D:\\proj\\poll-app\\server\\node_modules\\pg\\lib\\connection.js:553:11)\n    at Connection.parseMessage (D:\\proj\\poll-app\\server\\node_modules\\pg\\lib\\connection.js:378:19)\n    at Socket.<anonymous> (D:\\proj\\poll-app\\server\\node_modules\\pg\\lib\\connection.js:119:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:597:20)","name":"error","length":113,"severity":"FATAL","code":"28P01","file":"auth.c","line":"328","routine":"auth_failed","v":1}
```

Need to do something... In this representation, it's unusable

**Comment by tresdosdos** [comment]
this issue fixed in this commit[https://github.com/tresdosdos/poll-app/pull/2/commits/797a6dbff3a5e760ce463a7e8544df83d583d6a3](url)
